// Path: android/settings.gradle
// این فایل مسئولیت معرفی تمام مخازن به کل پروژه را بر عهده دارد

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
   
        maven {
            url 'https://storage.googleapis.com/download.flutter.io'
        }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        
        maven {
            url 'https://storage.googleapis.com/download.flutter.io'
        }
    }
}

rootProject.name = "android"
include ':app'
