name: Build Flutter App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # مرحله ۱: دریافت کد از ریپازیتوری
      - uses: actions/checkout@v4

      # مرحله ۲: نصب فلاتر
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # مرحله ۳: نصب پکیج‌ها
      - run: flutter pub get

      # مرحله ۴: اجرای دستور ساخت آیکون‌ها
      - run: flutter pub run flutter_launcher_icons:main

      # --- مراحل جدید برای ساخت Release APK ---

      # مرحله ۵: ایجاد فایل key.properties از Secret
      - name: Create key.properties
        run: echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      # مرحله ۶: ایجاد فایل keystore از Secret (Base64)
      - name: Create upload-keystore.jks
        run: echo "${{ secrets.KEYSTORE_JKS_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      # مرحله ۷: ساخت فایل APK نهایی
      - name: Build Release APK
        run: flutter build apk --release --split-per-abi

      # مرحله ۸: آپلود فایل‌های APK به عنوان Artifact
      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: build/app/outputs/flutter-apk/
